apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: standardization-backend-ingress
  annotations:
    # generic ingress annotation, can be overridden in overlays
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.standardization-backend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: standardization-backend-api
                port:
                  number: 8888
