apiVersion: v1
kind: Secret
metadata:
  name: standardization-backend-secret
  labels:
    app: standardization-backend
type: Opaque
stringData:
  # 数据库敏感信息
  DB_PASSWORD: "123456"
  
  # 认证密钥
  ACCESS_SECRET: "50e2129aa4e29021d7aeb5ee1e65580229dee62ef305994dce9caf9481ec24f8"
  
  # Redis 密码 (如果使用)
  REDIS_PASSWORD: ""
