apiVersion: v1
kind: Secret
metadata:
  name: standardization-backend-secret
  labels:
    app: standardization-backend
type: Opaque
stringData:
  # 数据库敏感信息
  DB_PASSWORD: "123456"
  
  # 认证密钥
  ACCESS_SECRET: "54b65ef50e67b1aeb14e8b56c30affc80c8edb14af769f1741bdb401f010ba30"
  
  # Redis 密码 (如果使用)
  REDIS_PASSWORD: ""
