# Default values for support.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: anyshare

image:
  registry: acr.xxx.cn
  pullPolicy: IfNotPresent
  repository: af/standardization/backend
  tag: "1.0.0-alpha"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
#需要暴露的端口号列表
#containerPort容器需要监听的端口号
#protocol端口协议，支持TCP和UDP，默认TCP
ports:
  name: server-port
  containerPort: 80


# 修改service的名字、端口，nodePort是对外的端口。
service:
  name: standardization
  type: ClusterIP
  port: 80
  oauthClientID: ""
  oauthClientSecret: ""

depServices:
  rds:
    host: 10.2.179.41
    port: 5236
    user: "SYSDBA"
    password: "HUN_SYSDBA2023"
    database: af_std
    type: DM8
  mq:
    Host: kafka-external-31000.resource
    Port: 9098
    Type: "kafka"
    auth:
      username: kafkaclient
      password: xxx
      mechanism: "PLAIN"
  class-443:
    ingressClass: class-443

config:
  backend:
    health: "/api/standardization/swagger-ui/index.html#/"
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

isDemo: false

ingress:
  host: standardization.xxx.cn
  tls:
    enabled: false
    secretName: xxx.cn

resources:
  requests:
    cpu: 0.2
    memory: 300Mi
  limits:
    cpu: 1
    memory: 2000Mi
  #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #   cpu: 100m
   # memory: 1500Mi
  #requests:
  #   cpu: 100m
   # memory: 1500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: []

tolerations: []

affinity: {}

oss:
  ossApp: af
  ossHost: ossgatewaymanager-private:9002
  ossProtocol: http
  ossIsDefault: true
  ossBucket: afstorage

#AF服务配置
afService:
  taskCenter:
    detailUrl: http://task-center:8143/api/task-center/v1/internal/tasks/%s